// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/task_service.proto

package taskservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateTaskRequest 创建任务请求
type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskType      string                 `protobuf:"bytes,1,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	Priority      int32                  `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"` // 0=Normal, 1=High
	Payload       map[string]string      `protobuf:"bytes,3,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_proto_task_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_task_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTaskRequest) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *CreateTaskRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *CreateTaskRequest) GetPayload() map[string]string {
	if x != nil {
		return x.Payload
	}
	return nil
}

// CreateTaskResponse 创建任务响应
type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_proto_task_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_task_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

// GetTaskRequest 查询任务请求
type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_proto_task_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_task_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// GetTaskResponse 查询任务响应
type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_proto_task_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_task_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

// CancelTaskRequest 取消任务请求
type CancelTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_proto_task_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_task_service_proto_rawDescGZIP(), []int{4}
}

func (x *CancelTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// CancelTaskResponse 取消任务响应
type CancelTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskResponse) Reset() {
	*x = CancelTaskResponse{}
	mi := &file_proto_task_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskResponse) ProtoMessage() {}

func (x *CancelTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskResponse.ProtoReflect.Descriptor instead.
func (*CancelTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_task_service_proto_rawDescGZIP(), []int{5}
}

func (x *CancelTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelTaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetTaskLogsRequest 获取任务日志请求
type GetTaskLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskLogsRequest) Reset() {
	*x = GetTaskLogsRequest{}
	mi := &file_proto_task_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskLogsRequest) ProtoMessage() {}

func (x *GetTaskLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskLogsRequest.ProtoReflect.Descriptor instead.
func (*GetTaskLogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_task_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetTaskLogsRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// GetTaskLogsResponse 获取任务日志响应
type GetTaskLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*TaskLog             `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskLogsResponse) Reset() {
	*x = GetTaskLogsResponse{}
	mi := &file_proto_task_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskLogsResponse) ProtoMessage() {}

func (x *GetTaskLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskLogsResponse.ProtoReflect.Descriptor instead.
func (*GetTaskLogsResponse) Descriptor() ([]byte, []int) {
	return file_proto_task_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetTaskLogsResponse) GetLogs() []*TaskLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

// ListTasksRequest 列出任务请求
type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`      // 可选：按状态过滤
	Priority      int32                  `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"` // 可选：按优先级过滤，-1表示不过滤
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_proto_task_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_proto_task_service_proto_rawDescGZIP(), []int{8}
}

func (x *ListTasksRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListTasksRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *ListTasksRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTasksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// ListTasksResponse 列出任务响应
type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_proto_task_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_proto_task_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ListTasksResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// Task 任务信息
type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskType      string                 `protobuf:"bytes,2,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Priority      int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	Payload       map[string]string      `protobuf:"bytes,5,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Result        map[string]string      `protobuf:"bytes,6,rep,name=result,proto3" json:"result,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	WorkerId      string                 `protobuf:"bytes,7,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	RetryCount    int32                  `protobuf:"varint,8,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	MaxRetry      int32                  `protobuf:"varint,9,opt,name=max_retry,json=maxRetry,proto3" json:"max_retry,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,10,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_proto_task_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_proto_task_service_proto_rawDescGZIP(), []int{10}
}

func (x *Task) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Task) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *Task) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Task) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Task) GetPayload() map[string]string {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Task) GetResult() map[string]string {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Task) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *Task) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *Task) GetMaxRetry() int32 {
	if x != nil {
		return x.MaxRetry
	}
	return 0
}

func (x *Task) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *Task) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Task) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Task) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

// TaskLog 任务日志
type TaskLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogId         string                 `protobuf:"bytes,1,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	LogType       string                 `protobuf:"bytes,3,opt,name=log_type,json=logType,proto3" json:"log_type,omitempty"`
	FromStatus    string                 `protobuf:"bytes,4,opt,name=from_status,json=fromStatus,proto3" json:"from_status,omitempty"`
	ToStatus      string                 `protobuf:"bytes,5,opt,name=to_status,json=toStatus,proto3" json:"to_status,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	WorkerId      string                 `protobuf:"bytes,7,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskLog) Reset() {
	*x = TaskLog{}
	mi := &file_proto_task_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskLog) ProtoMessage() {}

func (x *TaskLog) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskLog.ProtoReflect.Descriptor instead.
func (*TaskLog) Descriptor() ([]byte, []int) {
	return file_proto_task_service_proto_rawDescGZIP(), []int{11}
}

func (x *TaskLog) GetLogId() string {
	if x != nil {
		return x.LogId
	}
	return ""
}

func (x *TaskLog) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskLog) GetLogType() string {
	if x != nil {
		return x.LogType
	}
	return ""
}

func (x *TaskLog) GetFromStatus() string {
	if x != nil {
		return x.FromStatus
	}
	return ""
}

func (x *TaskLog) GetToStatus() string {
	if x != nil {
		return x.ToStatus
	}
	return ""
}

func (x *TaskLog) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TaskLog) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *TaskLog) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_proto_task_service_proto protoreflect.FileDescriptor

const file_proto_task_service_proto_rawDesc = "" +
	"\n" +
	"\x18proto/task_service.proto\x12\vtaskservice\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcf\x01\n" +
	"\x11CreateTaskRequest\x12\x1b\n" +
	"\ttask_type\x18\x01 \x01(\tR\btaskType\x12\x1a\n" +
	"\bpriority\x18\x02 \x01(\x05R\bpriority\x12E\n" +
	"\apayload\x18\x03 \x03(\v2+.taskservice.CreateTaskRequest.PayloadEntryR\apayload\x1a:\n" +
	"\fPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\";\n" +
	"\x12CreateTaskResponse\x12%\n" +
	"\x04task\x18\x01 \x01(\v2\x11.taskservice.TaskR\x04task\")\n" +
	"\x0eGetTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"8\n" +
	"\x0fGetTaskResponse\x12%\n" +
	"\x04task\x18\x01 \x01(\v2\x11.taskservice.TaskR\x04task\",\n" +
	"\x11CancelTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"H\n" +
	"\x12CancelTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"-\n" +
	"\x12GetTaskLogsRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"?\n" +
	"\x13GetTaskLogsResponse\x12(\n" +
	"\x04logs\x18\x01 \x03(\v2\x14.taskservice.TaskLogR\x04logs\"w\n" +
	"\x10ListTasksRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1a\n" +
	"\bpriority\x18\x02 \x01(\x05R\bpriority\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"R\n" +
	"\x11ListTasksResponse\x12'\n" +
	"\x05tasks\x18\x01 \x03(\v2\x11.taskservice.TaskR\x05tasks\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x8d\x05\n" +
	"\x04Task\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\ttask_type\x18\x02 \x01(\tR\btaskType\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\x128\n" +
	"\apayload\x18\x05 \x03(\v2\x1e.taskservice.Task.PayloadEntryR\apayload\x125\n" +
	"\x06result\x18\x06 \x03(\v2\x1d.taskservice.Task.ResultEntryR\x06result\x12\x1b\n" +
	"\tworker_id\x18\a \x01(\tR\bworkerId\x12\x1f\n" +
	"\vretry_count\x18\b \x01(\x05R\n" +
	"retryCount\x12\x1b\n" +
	"\tmax_retry\x18\t \x01(\x05R\bmaxRetry\x12#\n" +
	"\rerror_message\x18\n" +
	" \x01(\tR\ferrorMessage\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"started_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x1a:\n" +
	"\fPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vResultEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x84\x02\n" +
	"\aTaskLog\x12\x15\n" +
	"\x06log_id\x18\x01 \x01(\tR\x05logId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x19\n" +
	"\blog_type\x18\x03 \x01(\tR\alogType\x12\x1f\n" +
	"\vfrom_status\x18\x04 \x01(\tR\n" +
	"fromStatus\x12\x1b\n" +
	"\tto_status\x18\x05 \x01(\tR\btoStatus\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12\x1b\n" +
	"\tworker_id\x18\a \x01(\tR\bworkerId\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2\x8f\x03\n" +
	"\vTaskService\x12M\n" +
	"\n" +
	"CreateTask\x12\x1e.taskservice.CreateTaskRequest\x1a\x1f.taskservice.CreateTaskResponse\x12D\n" +
	"\aGetTask\x12\x1b.taskservice.GetTaskRequest\x1a\x1c.taskservice.GetTaskResponse\x12M\n" +
	"\n" +
	"CancelTask\x12\x1e.taskservice.CancelTaskRequest\x1a\x1f.taskservice.CancelTaskResponse\x12P\n" +
	"\vGetTaskLogs\x12\x1f.taskservice.GetTaskLogsRequest\x1a .taskservice.GetTaskLogsResponse\x12J\n" +
	"\tListTasks\x12\x1d.taskservice.ListTasksRequest\x1a\x1e.taskservice.ListTasksResponseB/Z-bamboo/cmd/asynctaskmanager/proto;taskserviceb\x06proto3"

var (
	file_proto_task_service_proto_rawDescOnce sync.Once
	file_proto_task_service_proto_rawDescData []byte
)

func file_proto_task_service_proto_rawDescGZIP() []byte {
	file_proto_task_service_proto_rawDescOnce.Do(func() {
		file_proto_task_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_task_service_proto_rawDesc), len(file_proto_task_service_proto_rawDesc)))
	})
	return file_proto_task_service_proto_rawDescData
}

var file_proto_task_service_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_task_service_proto_goTypes = []any{
	(*CreateTaskRequest)(nil),     // 0: taskservice.CreateTaskRequest
	(*CreateTaskResponse)(nil),    // 1: taskservice.CreateTaskResponse
	(*GetTaskRequest)(nil),        // 2: taskservice.GetTaskRequest
	(*GetTaskResponse)(nil),       // 3: taskservice.GetTaskResponse
	(*CancelTaskRequest)(nil),     // 4: taskservice.CancelTaskRequest
	(*CancelTaskResponse)(nil),    // 5: taskservice.CancelTaskResponse
	(*GetTaskLogsRequest)(nil),    // 6: taskservice.GetTaskLogsRequest
	(*GetTaskLogsResponse)(nil),   // 7: taskservice.GetTaskLogsResponse
	(*ListTasksRequest)(nil),      // 8: taskservice.ListTasksRequest
	(*ListTasksResponse)(nil),     // 9: taskservice.ListTasksResponse
	(*Task)(nil),                  // 10: taskservice.Task
	(*TaskLog)(nil),               // 11: taskservice.TaskLog
	nil,                           // 12: taskservice.CreateTaskRequest.PayloadEntry
	nil,                           // 13: taskservice.Task.PayloadEntry
	nil,                           // 14: taskservice.Task.ResultEntry
	(*timestamppb.Timestamp)(nil), // 15: google.protobuf.Timestamp
}
var file_proto_task_service_proto_depIdxs = []int32{
	12, // 0: taskservice.CreateTaskRequest.payload:type_name -> taskservice.CreateTaskRequest.PayloadEntry
	10, // 1: taskservice.CreateTaskResponse.task:type_name -> taskservice.Task
	10, // 2: taskservice.GetTaskResponse.task:type_name -> taskservice.Task
	11, // 3: taskservice.GetTaskLogsResponse.logs:type_name -> taskservice.TaskLog
	10, // 4: taskservice.ListTasksResponse.tasks:type_name -> taskservice.Task
	13, // 5: taskservice.Task.payload:type_name -> taskservice.Task.PayloadEntry
	14, // 6: taskservice.Task.result:type_name -> taskservice.Task.ResultEntry
	15, // 7: taskservice.Task.created_at:type_name -> google.protobuf.Timestamp
	15, // 8: taskservice.Task.started_at:type_name -> google.protobuf.Timestamp
	15, // 9: taskservice.Task.completed_at:type_name -> google.protobuf.Timestamp
	15, // 10: taskservice.TaskLog.created_at:type_name -> google.protobuf.Timestamp
	0,  // 11: taskservice.TaskService.CreateTask:input_type -> taskservice.CreateTaskRequest
	2,  // 12: taskservice.TaskService.GetTask:input_type -> taskservice.GetTaskRequest
	4,  // 13: taskservice.TaskService.CancelTask:input_type -> taskservice.CancelTaskRequest
	6,  // 14: taskservice.TaskService.GetTaskLogs:input_type -> taskservice.GetTaskLogsRequest
	8,  // 15: taskservice.TaskService.ListTasks:input_type -> taskservice.ListTasksRequest
	1,  // 16: taskservice.TaskService.CreateTask:output_type -> taskservice.CreateTaskResponse
	3,  // 17: taskservice.TaskService.GetTask:output_type -> taskservice.GetTaskResponse
	5,  // 18: taskservice.TaskService.CancelTask:output_type -> taskservice.CancelTaskResponse
	7,  // 19: taskservice.TaskService.GetTaskLogs:output_type -> taskservice.GetTaskLogsResponse
	9,  // 20: taskservice.TaskService.ListTasks:output_type -> taskservice.ListTasksResponse
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_task_service_proto_init() }
func file_proto_task_service_proto_init() {
	if File_proto_task_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_task_service_proto_rawDesc), len(file_proto_task_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_task_service_proto_goTypes,
		DependencyIndexes: file_proto_task_service_proto_depIdxs,
		MessageInfos:      file_proto_task_service_proto_msgTypes,
	}.Build()
	File_proto_task_service_proto = out.File
	file_proto_task_service_proto_goTypes = nil
	file_proto_task_service_proto_depIdxs = nil
}
